### PR TITLE
Add racket steps as exercise type

### PR DESCRIPTION
**Pull request by jchiam**
Support racketeers. Racketeers want prata too.

Conversion rate: 1200 steps (about 1km) to 100 coins

### CODE REVIEW

**Review by fonglh — CHANGES_REQUESTED** [review]
Enforce an upper limit for racket steps.

**Comment by jchiam** [comment]
What would be an appropriate upper bound? 15k?

**Comment by fonglh** [comment]
About 2 hours based on your fitbit data?

**Comment by jchiam** [comment]
Let's make it three then. I don't think I've gone past three non-stop before. 13k should be safe.

**Comment by jchiam** [comment]
@fonglh Upper bound for racket steps set to 13k

**Review by fonglh — APPROVED** [review]

**Pull request merged**
